<?php

class Countries {

  public function populate() {
    return array(
      (object) array('code' => 'af', 'continent' => 'AS', 'name' => "Afghanistan", 'iso' => 'AFG', 'number' => '004', 'fullname' => "Islamic Republic of Afghanistan"),
      (object) array('code' => 'ax', 'continent' => 'EU', 'name' => "Aland Islands", 'iso' => 'ALA', 'number' => '248', 'fullname' => "Aland Islands"),
      (object) array('code' => 'al', 'continent' => 'EU', 'name' => "Albania", 'iso' => 'ALB', 'number' => '008', 'fullname' => "Republic of Albania"),
      (object) array('code' => 'dz', 'continent' => 'AF', 'name' => "Algeria", 'iso' => 'DZA', 'number' => '012', 'fullname' => "People's Democratic Republic of Algeria"),
      (object) array('code' => 'as', 'continent' => 'OC', 'name' => "American Samoa", 'iso' => 'ASM', 'number' => '016', 'fullname' => "American Samoa"),
      (object) array('code' => 'ad', 'continent' => 'EU', 'name' => "Andorra", 'iso' => 'AND', 'number' => '020', 'fullname' => "Principality of Andorra"),
      (object) array('code' => 'ao', 'continent' => 'AF', 'name' => "Angola", 'iso' => 'AGO', 'number' => '024', 'fullname' => "Republic of Angola"),
      (object) array('code' => 'ai', 'continent' => 'NA', 'name' => "Anguilla", 'iso' => 'AIA', 'number' => '660', 'fullname' => "Anguilla"),
      (object) array('code' => 'aq', 'continent' => 'AN', 'name' => "Antarctica", 'iso' => 'ATA', 'number' => '010', 'fullname' => "Antarctica (the territory South of 60 deg S)"),
      (object) array('code' => 'ag', 'continent' => 'NA', 'name' => "Antigua and Barbuda", 'iso' => 'ATG', 'number' => '028', 'fullname' => "Antigua and Barbuda"),
      (object) array('code' => 'ar', 'continent' => 'SA', 'name' => "Argentina", 'iso' => 'ARG', 'number' => '032', 'fullname' => "Argentine Republic"),
      (object) array('code' => 'am', 'continent' => 'AS', 'name' => "Armenia", 'iso' => 'ARM', 'number' => '051', 'fullname' => "Republic of Armenia"),
      (object) array('code' => 'aw', 'continent' => 'NA', 'name' => "Aruba", 'iso' => 'ABW', 'number' => '533', 'fullname' => "Aruba"),
      (object) array('code' => 'au', 'continent' => 'OC', 'name' => "Australia", 'iso' => 'AUS', 'number' => '036', 'fullname' => "Commonwealth of Australia"),
      (object) array('code' => 'at', 'continent' => 'EU', 'name' => "Austria", 'iso' => 'AUT', 'number' => '040', 'fullname' => "Republic of Austria"),
      (object) array('code' => 'az', 'continent' => 'AS', 'name' => "Azerbaijan", 'iso' => 'AZE', 'number' => '031', 'fullname' => "Republic of Azerbaijan"),
      (object) array('code' => 'bs', 'continent' => 'NA', 'name' => "Bahamas", 'iso' => 'BHS', 'number' => '044', 'fullname' => "Commonwealth of the Bahamas"),
      (object) array('code' => 'bh', 'continent' => 'AS', 'name' => "Bahrain", 'iso' => 'BHR', 'number' => '048', 'fullname' => "Kingdom of Bahrain"),
      (object) array('code' => 'bd', 'continent' => 'AS', 'name' => "Bangladesh", 'iso' => 'BGD', 'number' => '050', 'fullname' => "People's Republic of Bangladesh"),
      (object) array('code' => 'bb', 'continent' => 'NA', 'name' => "Barbados", 'iso' => 'BRB', 'number' => '052', 'fullname' => "Barbados"),
      (object) array('code' => 'by', 'continent' => 'EU', 'name' => "Belarus", 'iso' => 'BLR', 'number' => '112', 'fullname' => "Republic of Belarus"),
      (object) array('code' => 'be', 'continent' => 'EU', 'name' => "Belgium", 'iso' => 'BEL', 'number' => '056', 'fullname' => "Kingdom of Belgium"),
      (object) array('code' => 'bz', 'continent' => 'NA', 'name' => "Belize", 'iso' => 'BLZ', 'number' => '084', 'fullname' => "Belize"),
      (object) array('code' => 'bj', 'continent' => 'AF', 'name' => "Benin", 'iso' => 'BEN', 'number' => '204', 'fullname' => "Republic of Benin"),
      (object) array('code' => 'bm', 'continent' => 'NA', 'name' => "Bermuda", 'iso' => 'BMU', 'number' => '060', 'fullname' => "Bermuda"),
      (object) array('code' => 'bt', 'continent' => 'AS', 'name' => "Bhutan", 'iso' => 'BTN', 'number' => '064', 'fullname' => "Kingdom of Bhutan"),
      (object) array('code' => 'bo', 'continent' => 'SA', 'name' => "Bolivia", 'iso' => 'BOL', 'number' => '068', 'fullname' => "Plurinational State of Bolivia"),
      (object) array('code' => 'bq', 'continent' => 'NA', 'name' => "Bonaire, Sint Eustatius and Saba", 'iso' => 'BES', 'number' => '535', 'fullname' => "Bonaire, Sint Eustatius and Saba"),
      (object) array('code' => 'ba', 'continent' => 'EU', 'name' => "Bosnia and Herzegovina", 'iso' => 'BIH', 'number' => '070', 'fullname' => "Bosnia and Herzegovina"),
      (object) array('code' => 'bw', 'continent' => 'AF', 'name' => "Botswana", 'iso' => 'BWA', 'number' => '072', 'fullname' => "Republic of Botswana"),
      (object) array('code' => 'bv', 'continent' => 'AN', 'name' => "Bouvet Island (Bouvetoya)", 'iso' => 'BVT', 'number' => '074', 'fullname' => "Bouvet Island (Bouvetoya)"),
      (object) array('code' => 'br', 'continent' => 'SA', 'name' => "Brazil", 'iso' => 'BRA', 'number' => '076', 'fullname' => "Federative Republic of Brazil"),
      (object) array('code' => 'io', 'continent' => 'AS', 'name' => "British Indian Ocean Territory (Chagos Archipelago)", 'iso' => 'IOT', 'number' => '086', 'fullname' => "British Indian Ocean Territory (Chagos Archipelago)"),
      (object) array('code' => 'vg', 'continent' => 'NA', 'name' => "British Virgin Islands", 'iso' => 'VGB', 'number' => '092', 'fullname' => "British Virgin Islands"),
      (object) array('code' => 'bn', 'continent' => 'AS', 'name' => "Brunei Darussalam", 'iso' => 'BRN', 'number' => '096', 'fullname' => "Brunei Darussalam"),
      (object) array('code' => 'bg', 'continent' => 'EU', 'name' => "Bulgaria", 'iso' => 'BGR', 'number' => '100', 'fullname' => "Republic of Bulgaria"),
      (object) array('code' => 'bf', 'continent' => 'AF', 'name' => "Burkina Faso", 'iso' => 'BFA', 'number' => '854', 'fullname' => "Burkina Faso"),
      (object) array('code' => 'bi', 'continent' => 'AF', 'name' => "Burundi", 'iso' => 'BDI', 'number' => '108', 'fullname' => "Republic of Burundi"),
      (object) array('code' => 'kh', 'continent' => 'AS', 'name' => "Cambodia", 'iso' => 'KHM', 'number' => '116', 'fullname' => "Kingdom of Cambodia"),
      (object) array('code' => 'cm', 'continent' => 'AF', 'name' => "Cameroon", 'iso' => 'CMR', 'number' => '120', 'fullname' => "Republic of Cameroon"),
      (object) array('code' => 'ca', 'continent' => 'NA', 'name' => "Canada", 'iso' => 'CAN', 'number' => '124', 'fullname' => "Canada"),
      (object) array('code' => 'cv', 'continent' => 'AF', 'name' => "Cape Verde", 'iso' => 'CPV', 'number' => '132', 'fullname' => "Republic of Cape Verde"),
      (object) array('code' => 'ky', 'continent' => 'NA', 'name' => "Cayman Islands", 'iso' => 'CYM', 'number' => '136', 'fullname' => "Cayman Islands"),
      (object) array('code' => 'cf', 'continent' => 'AF', 'name' => "Central African Republic", 'iso' => 'CAF', 'number' => '140', 'fullname' => "Central African Republic"),
      (object) array('code' => 'td', 'continent' => 'AF', 'name' => "Chad", 'iso' => 'TCD', 'number' => '148', 'fullname' => "Republic of Chad"),
      (object) array('code' => 'cl', 'continent' => 'SA', 'name' => "Chile", 'iso' => 'CHL', 'number' => '152', 'fullname' => "Republic of Chile"),
      (object) array('code' => 'cn', 'continent' => 'AS', 'name' => "China", 'iso' => 'CHN', 'number' => '156', 'fullname' => "People's Republic of China"),
      (object) array('code' => 'cx', 'continent' => 'AS', 'name' => "Christmas Island", 'iso' => 'CXR', 'number' => '162', 'fullname' => "Christmas Island"),
      (object) array('code' => 'cc', 'continent' => 'AS', 'name' => "Cocos (Keeling) Islands", 'iso' => 'CCK', 'number' => '166', 'fullname' => "Cocos (Keeling) Islands"),
      (object) array('code' => 'co', 'continent' => 'SA', 'name' => "Colombia", 'iso' => 'COL', 'number' => '170', 'fullname' => "Republic of Colombia"),
      (object) array('code' => 'km', 'continent' => 'AF', 'name' => "Comoros", 'iso' => 'COM', 'number' => '174', 'fullname' => "Union of the Comoros"),
      (object) array('code' => 'cd', 'continent' => 'AF', 'name' => "Congo", 'iso' => 'COD', 'number' => '180', 'fullname' => "Democratic Republic of the Congo"),
      (object) array('code' => 'cg', 'continent' => 'AF', 'name' => "Congo", 'iso' => 'COG', 'number' => '178', 'fullname' => "Republic of the Congo"),
      (object) array('code' => 'ck', 'continent' => 'OC', 'name' => "Cook Islands", 'iso' => 'COK', 'number' => '184', 'fullname' => "Cook Islands"),
      (object) array('code' => 'cr', 'continent' => 'NA', 'name' => "Costa Rica", 'iso' => 'CRI', 'number' => '188', 'fullname' => "Republic of Costa Rica"),
      (object) array('code' => 'ci', 'continent' => 'AF', 'name' => "Cote d'Ivoire", 'iso' => 'CIV', 'number' => '384', 'fullname' => "Republic of Cote d'Ivoire"),
      (object) array('code' => 'hr', 'continent' => 'EU', 'name' => "Croatia", 'iso' => 'HRV', 'number' => '191', 'fullname' => "Republic of Croatia"),
      (object) array('code' => 'cu', 'continent' => 'NA', 'name' => "Cuba", 'iso' => 'CUB', 'number' => '192', 'fullname' => "Republic of Cuba"),
      (object) array('code' => 'cw', 'continent' => 'NA', 'name' => "Curaçao", 'iso' => 'CUW', 'number' => '531', 'fullname' => "Curaçao"),
      (object) array('code' => 'cy', 'continent' => 'AS', 'name' => "Cyprus", 'iso' => 'CYP', 'number' => '196', 'fullname' => "Republic of Cyprus"),
      (object) array('code' => 'cz', 'continent' => 'EU', 'name' => "Czech Republic", 'iso' => 'CZE', 'number' => '203', 'fullname' => "Czech Republic"),
      (object) array('code' => 'dk', 'continent' => 'EU', 'name' => "Denmark", 'iso' => 'DNK', 'number' => '208', 'fullname' => "Kingdom of Denmark"),
      (object) array('code' => 'dj', 'continent' => 'AF', 'name' => "Djibouti", 'iso' => 'DJI', 'number' => '262', 'fullname' => "Republic of Djibouti"),
      (object) array('code' => 'dm', 'continent' => 'NA', 'name' => "Dominica", 'iso' => 'DMA', 'number' => '212', 'fullname' => "Commonwealth of Dominica"),
      (object) array('code' => 'do', 'continent' => 'NA', 'name' => "Dominican Republic", 'iso' => 'DOM', 'number' => '214', 'fullname' => "Dominican Republic"),
      (object) array('code' => 'ec', 'continent' => 'SA', 'name' => "Ecuador", 'iso' => 'ECU', 'number' => '218', 'fullname' => "Republic of Ecuador"),
      (object) array('code' => 'eg', 'continent' => 'AF', 'name' => "Egypt", 'iso' => 'EGY', 'number' => '818', 'fullname' => "Arab Republic of Egypt"),
      (object) array('code' => 'sv', 'continent' => 'NA', 'name' => "El Salvador", 'iso' => 'SLV', 'number' => '222', 'fullname' => "Republic of El Salvador"),
      (object) array('code' => 'gq', 'continent' => 'AF', 'name' => "Equatorial Guinea", 'iso' => 'GNQ', 'number' => '226', 'fullname' => "Republic of Equatorial Guinea"),
      (object) array('code' => 'er', 'continent' => 'AF', 'name' => "Eritrea", 'iso' => 'ERI', 'number' => '232', 'fullname' => "State of Eritrea"),
      (object) array('code' => 'ee', 'continent' => 'EU', 'name' => "Estonia", 'iso' => 'EST', 'number' => '233', 'fullname' => "Republic of Estonia"),
      (object) array('code' => 'et', 'continent' => 'AF', 'name' => "Ethiopia", 'iso' => 'ETH', 'number' => '231', 'fullname' => "Federal Democratic Republic of Ethiopia"),
      (object) array('code' => 'fo', 'continent' => 'EU', 'name' => "Faroe Islands", 'iso' => 'FRO', 'number' => '234', 'fullname' => "Faroe Islands"),
      (object) array('code' => 'fk', 'continent' => 'SA', 'name' => "Falkland Islands (Malvinas)", 'iso' => 'FLK', 'number' => '238', 'fullname' => "Falkland Islands (Malvinas)"),
      (object) array('code' => 'fj', 'continent' => 'OC', 'name' => "Fiji", 'iso' => 'FJI', 'number' => '242', 'fullname' => "Republic of Fiji"),
      (object) array('code' => 'fi', 'continent' => 'EU', 'name' => "Finland", 'iso' => 'FIN', 'number' => '246', 'fullname' => "Republic of Finland"),
      (object) array('code' => 'fr', 'continent' => 'EU', 'name' => "France", 'iso' => 'FRA', 'number' => '250', 'fullname' => "French Republic"),
      (object) array('code' => 'gf', 'continent' => 'SA', 'name' => "French Guiana", 'iso' => 'GUF', 'number' => '254', 'fullname' => "French Guiana"),
      (object) array('code' => 'pf', 'continent' => 'OC', 'name' => "French Polynesia", 'iso' => 'PYF', 'number' => '258', 'fullname' => "French Polynesia"),
      (object) array('code' => 'tf', 'continent' => 'AN', 'name' => "French Southern Territories", 'iso' => 'ATF', 'number' => '260', 'fullname' => "French Southern Territories"),
      (object) array('code' => 'ga', 'continent' => 'AF', 'name' => "Gabon", 'iso' => 'GAB', 'number' => '266', 'fullname' => "Gabonese Republic"),
      (object) array('code' => 'gm', 'continent' => 'AF', 'name' => "Gambia", 'iso' => 'GMB', 'number' => '270', 'fullname' => "Republic of the Gambia"),
      (object) array('code' => 'ge', 'continent' => 'AS', 'name' => "Georgia", 'iso' => 'GEO', 'number' => '268', 'fullname' => "Georgia"),
      (object) array('code' => 'de', 'continent' => 'EU', 'name' => "Germany", 'iso' => 'DEU', 'number' => '276', 'fullname' => "Federal Republic of Germany"),
      (object) array('code' => 'gh', 'continent' => 'AF', 'name' => "Ghana", 'iso' => 'GHA', 'number' => '288', 'fullname' => "Republic of Ghana"),
      (object) array('code' => 'gi', 'continent' => 'EU', 'name' => "Gibraltar", 'iso' => 'GIB', 'number' => '292', 'fullname' => "Gibraltar"),
      (object) array('code' => 'gr', 'continent' => 'EU', 'name' => "Greece", 'iso' => 'GRC', 'number' => '300', 'fullname' => "Hellenic Republic Greece"),
      (object) array('code' => 'gl', 'continent' => 'NA', 'name' => "Greenland", 'iso' => 'GRL', 'number' => '304', 'fullname' => "Greenland"),
      (object) array('code' => 'gd', 'continent' => 'NA', 'name' => "Grenada", 'iso' => 'GRD', 'number' => '308', 'fullname' => "Grenada"),
      (object) array('code' => 'gp', 'continent' => 'NA', 'name' => "Guadeloupe", 'iso' => 'GLP', 'number' => '312', 'fullname' => "Guadeloupe"),
      (object) array('code' => 'gu', 'continent' => 'OC', 'name' => "Guam", 'iso' => 'GUM', 'number' => '316', 'fullname' => "Guam"),
      (object) array('code' => 'gt', 'continent' => 'NA', 'name' => "Guatemala", 'iso' => 'GTM', 'number' => '320', 'fullname' => "Republic of Guatemala"),
      (object) array('code' => 'gg', 'continent' => 'EU', 'name' => "Guernsey", 'iso' => 'GGY', 'number' => '831', 'fullname' => "Bailiwick of Guernsey"),
      (object) array('code' => 'gn', 'continent' => 'AF', 'name' => "Guinea", 'iso' => 'GIN', 'number' => '324', 'fullname' => "Republic of Guinea"),
      (object) array('code' => 'gw', 'continent' => 'AF', 'name' => "Guinea-Bissau", 'iso' => 'GNB', 'number' => '624', 'fullname' => "Republic of Guinea-Bissau"),
      (object) array('code' => 'gy', 'continent' => 'SA', 'name' => "Guyana", 'iso' => 'GUY', 'number' => '328', 'fullname' => "Co-operative Republic of Guyana"),
      (object) array('code' => 'ht', 'continent' => 'NA', 'name' => "Haiti", 'iso' => 'HTI', 'number' => '332', 'fullname' => "Republic of Haiti"),
      (object) array('code' => 'hm', 'continent' => 'AN', 'name' => "Heard Island and McDonald Islands", 'iso' => 'HMD', 'number' => '334', 'fullname' => "Heard Island and McDonald Islands"),
      (object) array('code' => 'va', 'continent' => 'EU', 'name' => "Holy See (Vatican City State)", 'iso' => 'VAT', 'number' => '336', 'fullname' => "Holy See (Vatican City State)"),
      (object) array('code' => 'hn', 'continent' => 'NA', 'name' => "Honduras", 'iso' => 'HND', 'number' => '340', 'fullname' => "Republic of Honduras"),
      (object) array('code' => 'hk', 'continent' => 'AS', 'name' => "Hong Kong", 'iso' => 'HKG', 'number' => '344', 'fullname' => "Hong Kong Special Administrative Region of China"),
      (object) array('code' => 'hu', 'continent' => 'EU', 'name' => "Hungary", 'iso' => 'HUN', 'number' => '348', 'fullname' => "Hungary"),
      (object) array('code' => 'is', 'continent' => 'EU', 'name' => "Iceland", 'iso' => 'ISL', 'number' => '352', 'fullname' => "Republic of Iceland"),
      (object) array('code' => 'in', 'continent' => 'AS', 'name' => "India", 'iso' => 'IND', 'number' => '356', 'fullname' => "Republic of India"),
      (object) array('code' => 'id', 'continent' => 'AS', 'name' => "Indonesia", 'iso' => 'IDN', 'number' => '360', 'fullname' => "Republic of Indonesia"),
      (object) array('code' => 'ir', 'continent' => 'AS', 'name' => "Iran", 'iso' => 'IRN', 'number' => '364', 'fullname' => "Islamic Republic of Iran"),
      (object) array('code' => 'iq', 'continent' => 'AS', 'name' => "Iraq", 'iso' => 'IRQ', 'number' => '368', 'fullname' => "Republic of Iraq"),
      (object) array('code' => 'ie', 'continent' => 'EU', 'name' => "Ireland", 'iso' => 'IRL', 'number' => '372', 'fullname' => "Ireland"),
      (object) array('code' => 'im', 'continent' => 'EU', 'name' => "Isle of Man", 'iso' => 'IMN', 'number' => '833', 'fullname' => "Isle of Man"),
      (object) array('code' => 'il', 'continent' => 'AS', 'name' => "Israel", 'iso' => 'ISR', 'number' => '376', 'fullname' => "State of Israel"),
      (object) array('code' => 'it', 'continent' => 'EU', 'name' => "Italy", 'iso' => 'ITA', 'number' => '380', 'fullname' => "Italian Republic"),
      (object) array('code' => 'jm', 'continent' => 'NA', 'name' => "Jamaica", 'iso' => 'JAM', 'number' => '388', 'fullname' => "Jamaica"),
      (object) array('code' => 'jp', 'continent' => 'AS', 'name' => "Japan", 'iso' => 'JPN', 'number' => '392', 'fullname' => "Japan"),
      (object) array('code' => 'je', 'continent' => 'EU', 'name' => "Jersey", 'iso' => 'JEY', 'number' => '832', 'fullname' => "Bailiwick of Jersey"),
      (object) array('code' => 'jo', 'continent' => 'AS', 'name' => "Jordan", 'iso' => 'JOR', 'number' => '400', 'fullname' => "Hashemite Kingdom of Jordan"),
      (object) array('code' => 'kz', 'continent' => 'AS', 'name' => "Kazakhstan", 'iso' => 'KAZ', 'number' => '398', 'fullname' => "Republic of Kazakhstan"),
      (object) array('code' => 'ke', 'continent' => 'AF', 'name' => "Kenya", 'iso' => 'KEN', 'number' => '404', 'fullname' => "Republic of Kenya"),
      (object) array('code' => 'ki', 'continent' => 'OC', 'name' => "Kiribati", 'iso' => 'KIR', 'number' => '296', 'fullname' => "Republic of Kiribati"),
      (object) array('code' => 'kp', 'continent' => 'AS', 'name' => "Korea", 'iso' => 'PRK', 'number' => '408', 'fullname' => "Democratic People's Republic of Korea"),
      (object) array('code' => 'kr', 'continent' => 'AS', 'name' => "Korea", 'iso' => 'KOR', 'number' => '410', 'fullname' => "Republic of Korea"),
      (object) array('code' => 'kw', 'continent' => 'AS', 'name' => "Kuwait", 'iso' => 'KWT', 'number' => '414', 'fullname' => "State of Kuwait"),
      (object) array('code' => 'kg', 'continent' => 'AS', 'name' => "Kyrgyz Republic", 'iso' => 'KGZ', 'number' => '417', 'fullname' => "Kyrgyz Republic"),
      (object) array('code' => 'la', 'continent' => 'AS', 'name' => "Lao People's Democratic Republic", 'iso' => 'LAO', 'number' => '418', 'fullname' => "Lao People's Democratic Republic"),
      (object) array('code' => 'lv', 'continent' => 'EU', 'name' => "Latvia", 'iso' => 'LVA', 'number' => '428', 'fullname' => "Republic of Latvia"),
      (object) array('code' => 'lb', 'continent' => 'AS', 'name' => "Lebanon", 'iso' => 'LBN', 'number' => '422', 'fullname' => "Lebanese Republic"),
      (object) array('code' => 'ls', 'continent' => 'AF', 'name' => "Lesotho", 'iso' => 'LSO', 'number' => '426', 'fullname' => "Kingdom of Lesotho"),
      (object) array('code' => 'lr', 'continent' => 'AF', 'name' => "Liberia", 'iso' => 'LBR', 'number' => '430', 'fullname' => "Republic of Liberia"),
      (object) array('code' => 'ly', 'continent' => 'AF', 'name' => "Libya", 'iso' => 'LBY', 'number' => '434', 'fullname' => "Libya"),
      (object) array('code' => 'li', 'continent' => 'EU', 'name' => "Liechtenstein", 'iso' => 'LIE', 'number' => '438', 'fullname' => "Principality of Liechtenstein"),
      (object) array('code' => 'lt', 'continent' => 'EU', 'name' => "Lithuania", 'iso' => 'LTU', 'number' => '440', 'fullname' => "Republic of Lithuania"),
      (object) array('code' => 'lu', 'continent' => 'EU', 'name' => "Luxembourg", 'iso' => 'LUX', 'number' => '442', 'fullname' => "Grand Duchy of Luxembourg"),
      (object) array('code' => 'mo', 'continent' => 'AS', 'name' => "Macao", 'iso' => 'MAC', 'number' => '446', 'fullname' => "Macao Special Administrative Region of China"),
      (object) array('code' => 'mk', 'continent' => 'EU', 'name' => "Macedonia", 'iso' => 'MKD', 'number' => '807', 'fullname' => "Republic of Macedonia"),
      (object) array('code' => 'mg', 'continent' => 'AF', 'name' => "Madagascar", 'iso' => 'MDG', 'number' => '450', 'fullname' => "Republic of Madagascar"),
      (object) array('code' => 'mw', 'continent' => 'AF', 'name' => "Malawi", 'iso' => 'MWI', 'number' => '454', 'fullname' => "Republic of Malawi"),
      (object) array('code' => 'my', 'continent' => 'AS', 'name' => "Malaysia", 'iso' => 'MYS', 'number' => '458', 'fullname' => "Malaysia"),
      (object) array('code' => 'mv', 'continent' => 'AS', 'name' => "Maldives", 'iso' => 'MDV', 'number' => '462', 'fullname' => "Republic of Maldives"),
      (object) array('code' => 'ml', 'continent' => 'AF', 'name' => "Mali", 'iso' => 'MLI', 'number' => '466', 'fullname' => "Republic of Mali"),
      (object) array('code' => 'mt', 'continent' => 'EU', 'name' => "Malta", 'iso' => 'MLT', 'number' => '470', 'fullname' => "Republic of Malta"),
      (object) array('code' => 'mh', 'continent' => 'OC', 'name' => "Marshall Islands", 'iso' => 'MHL', 'number' => '584', 'fullname' => "Republic of the Marshall Islands"),
      (object) array('code' => 'mq', 'continent' => 'NA', 'name' => "Martinique", 'iso' => 'MTQ', 'number' => '474', 'fullname' => "Martinique"),
      (object) array('code' => 'mr', 'continent' => 'AF', 'name' => "Mauritania", 'iso' => 'MRT', 'number' => '478', 'fullname' => "Islamic Republic of Mauritania"),
      (object) array('code' => 'mu', 'continent' => 'AF', 'name' => "Mauritius", 'iso' => 'MUS', 'number' => '480', 'fullname' => "Republic of Mauritius"),
      (object) array('code' => 'yt', 'continent' => 'AF', 'name' => "Mayotte", 'iso' => 'MYT', 'number' => '175', 'fullname' => "Mayotte"),
      (object) array('code' => 'mx', 'continent' => 'NA', 'name' => "Mexico", 'iso' => 'MEX', 'number' => '484', 'fullname' => "United Mexican States"),
      (object) array('code' => 'fm', 'continent' => 'OC', 'name' => "Micronesia", 'iso' => 'FSM', 'number' => '583', 'fullname' => "Federated States of Micronesia"),
      (object) array('code' => 'md', 'continent' => 'EU', 'name' => "Moldova", 'iso' => 'MDA', 'number' => '498', 'fullname' => "Republic of Moldova"),
      (object) array('code' => 'mc', 'continent' => 'EU', 'name' => "Monaco", 'iso' => 'MCO', 'number' => '492', 'fullname' => "Principality of Monaco"),
      (object) array('code' => 'mn', 'continent' => 'AS', 'name' => "Mongolia", 'iso' => 'MNG', 'number' => '496', 'fullname' => "Mongolia"),
      (object) array('code' => 'me', 'continent' => 'EU', 'name' => "Montenegro", 'iso' => 'MNE', 'number' => '499', 'fullname' => "Montenegro"),
      (object) array('code' => 'ms', 'continent' => 'NA', 'name' => "Montserrat", 'iso' => 'MSR', 'number' => '500', 'fullname' => "Montserrat"),
      (object) array('code' => 'ma', 'continent' => 'AF', 'name' => "Morocco", 'iso' => 'MAR', 'number' => '504', 'fullname' => "Kingdom of Morocco"),
      (object) array('code' => 'mz', 'continent' => 'AF', 'name' => "Mozambique", 'iso' => 'MOZ', 'number' => '508', 'fullname' => "Republic of Mozambique"),
      (object) array('code' => 'mm', 'continent' => 'AS', 'name' => "Myanmar", 'iso' => 'MMR', 'number' => '104', 'fullname' => "Republic of the Union of Myanmar"),
      (object) array('code' => 'na', 'continent' => 'AF', 'name' => "Namibia", 'iso' => 'NAM', 'number' => '516', 'fullname' => "Republic of Namibia"),
      (object) array('code' => 'nr', 'continent' => 'OC', 'name' => "Nauru", 'iso' => 'NRU', 'number' => '520', 'fullname' => "Republic of Nauru"),
      (object) array('code' => 'np', 'continent' => 'AS', 'name' => "Nepal", 'iso' => 'NPL', 'number' => '524', 'fullname' => "Federal Democratic Republic of Nepal"),
      (object) array('code' => 'nl', 'continent' => 'EU', 'name' => "Netherlands", 'iso' => 'NLD', 'number' => '528', 'fullname' => "Kingdom of the Netherlands"),
      (object) array('code' => 'nc', 'continent' => 'OC', 'name' => "New Caledonia", 'iso' => 'NCL', 'number' => '540', 'fullname' => "New Caledonia"),
      (object) array('code' => 'nz', 'continent' => 'OC', 'name' => "New Zealand", 'iso' => 'NZL', 'number' => '554', 'fullname' => "New Zealand"),
      (object) array('code' => 'ni', 'continent' => 'NA', 'name' => "Nicaragua", 'iso' => 'NIC', 'number' => '558', 'fullname' => "Republic of Nicaragua"),
      (object) array('code' => 'ne', 'continent' => 'AF', 'name' => "Niger", 'iso' => 'NER', 'number' => '562', 'fullname' => "Republic of Niger"),
      (object) array('code' => 'ng', 'continent' => 'AF', 'name' => "Nigeria", 'iso' => 'NGA', 'number' => '566', 'fullname' => "Federal Republic of Nigeria"),
      (object) array('code' => 'nu', 'continent' => 'OC', 'name' => "Niue", 'iso' => 'NIU', 'number' => '570', 'fullname' => "Niue"),
      (object) array('code' => 'nf', 'continent' => 'OC', 'name' => "Norfolk Island", 'iso' => 'NFK', 'number' => '574', 'fullname' => "Norfolk Island"),
      (object) array('code' => 'mp', 'continent' => 'OC', 'name' => "Northern Mariana Islands", 'iso' => 'MNP', 'number' => '580', 'fullname' => "Commonwealth of the Northern Mariana Islands"),
      (object) array('code' => 'no', 'continent' => 'EU', 'name' => "Norway", 'iso' => 'NOR', 'number' => '578', 'fullname' => "Kingdom of Norway"),
      (object) array('code' => 'om', 'continent' => 'AS', 'name' => "Oman", 'iso' => 'OMN', 'number' => '512', 'fullname' => "Sultanate of Oman"),
      (object) array('code' => 'pk', 'continent' => 'AS', 'name' => "Pakistan", 'iso' => 'PAK', 'number' => '586', 'fullname' => "Islamic Republic of Pakistan"),
      (object) array('code' => 'pw', 'continent' => 'OC', 'name' => "Palau", 'iso' => 'PLW', 'number' => '585', 'fullname' => "Republic of Palau"),
      (object) array('code' => 'ps', 'continent' => 'AS', 'name' => "Palestinian Territory", 'iso' => 'PSE', 'number' => '275', 'fullname' => "Occupied Palestinian Territory"),
      (object) array('code' => 'pa', 'continent' => 'NA', 'name' => "Panama", 'iso' => 'PAN', 'number' => '591', 'fullname' => "Republic of Panama"),
      (object) array('code' => 'pg', 'continent' => 'OC', 'name' => "Papua New Guinea", 'iso' => 'PNG', 'number' => '598', 'fullname' => "Independent State of Papua New Guinea"),
      (object) array('code' => 'py', 'continent' => 'SA', 'name' => "Paraguay", 'iso' => 'PRY', 'number' => '600', 'fullname' => "Republic of Paraguay"),
      (object) array('code' => 'pe', 'continent' => 'SA', 'name' => "Peru", 'iso' => 'PER', 'number' => '604', 'fullname' => "Republic of Peru"),
      (object) array('code' => 'ph', 'continent' => 'AS', 'name' => "Philippines", 'iso' => 'PHL', 'number' => '608', 'fullname' => "Republic of the Philippines"),
      (object) array('code' => 'pn', 'continent' => 'OC', 'name' => "Pitcairn Islands", 'iso' => 'PCN', 'number' => '612', 'fullname' => "Pitcairn Islands"),
      (object) array('code' => 'pl', 'continent' => 'EU', 'name' => "Poland", 'iso' => 'POL', 'number' => '616', 'fullname' => "Republic of Poland"),
      (object) array('code' => 'pt', 'continent' => 'EU', 'name' => "Portugal", 'iso' => 'PRT', 'number' => '620', 'fullname' => "Portuguese Republic"),
      (object) array('code' => 'pr', 'continent' => 'NA', 'name' => "Puerto Rico", 'iso' => 'PRI', 'number' => '630', 'fullname' => "Commonwealth of Puerto Rico"),
      (object) array('code' => 'qa', 'continent' => 'AS', 'name' => "Qatar", 'iso' => 'QAT', 'number' => '634', 'fullname' => "State of Qatar"),
      (object) array('code' => 're', 'continent' => 'AF', 'name' => "Réunion", 'iso' => 'REU', 'number' => '638', 'fullname' => "Réunion"),
      (object) array('code' => 'ro', 'continent' => 'EU', 'name' => "Romania", 'iso' => 'ROU', 'number' => '642', 'fullname' => "Romania"),
      (object) array('code' => 'ru', 'continent' => 'EU', 'name' => "Russian Federation", 'iso' => 'RUS', 'number' => '643', 'fullname' => "Russian Federation"),
      (object) array('code' => 'rw', 'continent' => 'AF', 'name' => "Rwanda", 'iso' => 'RWA', 'number' => '646', 'fullname' => "Republic of Rwanda"),
      (object) array('code' => 'bl', 'continent' => 'NA', 'name' => "Saint Barthelemy", 'iso' => 'BLM', 'number' => '652', 'fullname' => "Saint Barthelemy"),
      (object) array('code' => 'sh', 'continent' => 'AF', 'name' => "Saint Helena, Ascension and Tristan da Cunha", 'iso' => 'SHN', 'number' => '654', 'fullname' => "Saint Helena, Ascension and Tristan da Cunha"),
      (object) array('code' => 'kn', 'continent' => 'NA', 'name' => "Saint Kitts and Nevis", 'iso' => 'KNA', 'number' => '659', 'fullname' => "Federation of Saint Kitts and Nevis"),
      (object) array('code' => 'lc', 'continent' => 'NA', 'name' => "Saint Lucia", 'iso' => 'LCA', 'number' => '662', 'fullname' => "Saint Lucia"),
      (object) array('code' => 'mf', 'continent' => 'NA', 'name' => "Saint Martin", 'iso' => 'MAF', 'number' => '663', 'fullname' => "Saint Martin (French part)"),
      (object) array('code' => 'pm', 'continent' => 'NA', 'name' => "Saint Pierre and Miquelon", 'iso' => 'SPM', 'number' => '666', 'fullname' => "Saint Pierre and Miquelon"),
      (object) array('code' => 'vc', 'continent' => 'NA', 'name' => "Saint Vincent and the Grenadines", 'iso' => 'VCT', 'number' => '670', 'fullname' => "Saint Vincent and the Grenadines"),
      (object) array('code' => 'ws', 'continent' => 'OC', 'name' => "Samoa", 'iso' => 'WSM', 'number' => '882', 'fullname' => "Independent State of Samoa"),
      (object) array('code' => 'sm', 'continent' => 'EU', 'name' => "San Marino", 'iso' => 'SMR', 'number' => '674', 'fullname' => "Republic of San Marino"),
      (object) array('code' => 'st', 'continent' => 'AF', 'name' => "Sao Tome and Principe", 'iso' => 'STP', 'number' => '678', 'fullname' => "Democratic Republic of Sao Tome and Principe"),
      (object) array('code' => 'sa', 'continent' => 'AS', 'name' => "Saudi Arabia", 'iso' => 'SAU', 'number' => '682', 'fullname' => "Kingdom of Saudi Arabia"),
      (object) array('code' => 'sn', 'continent' => 'AF', 'name' => "Senegal", 'iso' => 'SEN', 'number' => '686', 'fullname' => "Republic of Senegal"),
      (object) array('code' => 'rs', 'continent' => 'EU', 'name' => "Serbia", 'iso' => 'SRB', 'number' => '688', 'fullname' => "Republic of Serbia"),
      (object) array('code' => 'sc', 'continent' => 'AF', 'name' => "Seychelles", 'iso' => 'SYC', 'number' => '690', 'fullname' => "Republic of Seychelles"),
      (object) array('code' => 'sl', 'continent' => 'AF', 'name' => "Sierra Leone", 'iso' => 'SLE', 'number' => '694', 'fullname' => "Republic of Sierra Leone"),
      (object) array('code' => 'sg', 'continent' => 'AS', 'name' => "Singapore", 'iso' => 'SGP', 'number' => '702', 'fullname' => "Republic of Singapore"),
      (object) array('code' => 'sx', 'continent' => 'NA', 'name' => "Sint Maarten (Dutch part)", 'iso' => 'SXM', 'number' => '534', 'fullname' => "Sint Maarten (Dutch part)"),
      (object) array('code' => 'sk', 'continent' => 'EU', 'name' => "Slovakia (Slovak Republic)", 'iso' => 'SVK', 'number' => '703', 'fullname' => "Slovakia (Slovak Republic)"),
      (object) array('code' => 'si', 'continent' => 'EU', 'name' => "Slovenia", 'iso' => 'SVN', 'number' => '705', 'fullname' => "Republic of Slovenia"),
      (object) array('code' => 'sb', 'continent' => 'OC', 'name' => "Solomon Islands", 'iso' => 'SLB', 'number' => '090', 'fullname' => "Solomon Islands"),
      (object) array('code' => 'so', 'continent' => 'AF', 'name' => "Somalia", 'iso' => 'SOM', 'number' => '706', 'fullname' => "Somali Republic"),
      (object) array('code' => 'za', 'continent' => 'AF', 'name' => "South Africa", 'iso' => 'ZAF', 'number' => '710', 'fullname' => "Republic of South Africa"),
      (object) array('code' => 'gs', 'continent' => 'AN', 'name' => "South Georgia and the South Sandwich Islands", 'iso' => 'SGS', 'number' => '239', 'fullname' => "South Georgia and the South Sandwich Islands"),
      (object) array('code' => 'ss', 'continent' => 'AF', 'name' => "South Sudan", 'iso' => 'SSD', 'number' => '728', 'fullname' => "Republic of South Sudan"),
      (object) array('code' => 'es', 'continent' => 'EU', 'name' => "Spain", 'iso' => 'ESP', 'number' => '724', 'fullname' => "Kingdom of Spain"),
      (object) array('code' => 'lk', 'continent' => 'AS', 'name' => "Sri Lanka", 'iso' => 'LKA', 'number' => '144', 'fullname' => "Democratic Socialist Republic of Sri Lanka"),
      (object) array('code' => 'sd', 'continent' => 'AF', 'name' => "Sudan", 'iso' => 'SDN', 'number' => '729', 'fullname' => "Republic of Sudan"),
      (object) array('code' => 'sr', 'continent' => 'SA', 'name' => "Suriname", 'iso' => 'SUR', 'number' => '740', 'fullname' => "Republic of Suriname"),
      (object) array('code' => 'sj', 'continent' => 'EU', 'name' => "Svalbard & Jan Mayen Islands", 'iso' => 'SJM', 'number' => '744', 'fullname' => "Svalbard & Jan Mayen Islands"),
      (object) array('code' => 'sz', 'continent' => 'AF', 'name' => "Swaziland", 'iso' => 'SWZ', 'number' => '748', 'fullname' => "Kingdom of Swaziland"),
      (object) array('code' => 'se', 'continent' => 'EU', 'name' => "Sweden", 'iso' => 'SWE', 'number' => '752', 'fullname' => "Kingdom of Sweden"),
      (object) array('code' => 'ch', 'continent' => 'EU', 'name' => "Switzerland", 'iso' => 'CHE', 'number' => '756', 'fullname' => "Swiss Confederation"),
      (object) array('code' => 'sy', 'continent' => 'AS', 'name' => "Syrian Arab Republic", 'iso' => 'SYR', 'number' => '760', 'fullname' => "Syrian Arab Republic"),
      (object) array('code' => 'tw', 'continent' => 'AS', 'name' => "Taiwan", 'iso' => 'TWN', 'number' => '158', 'fullname' => "Taiwan, Province of China"),
      (object) array('code' => 'tj', 'continent' => 'AS', 'name' => "Tajikistan", 'iso' => 'TJK', 'number' => '762', 'fullname' => "Republic of Tajikistan"),
      (object) array('code' => 'tz', 'continent' => 'AF', 'name' => "Tanzania", 'iso' => 'TZA', 'number' => '834', 'fullname' => "United Republic of Tanzania"),
      (object) array('code' => 'th', 'continent' => 'AS', 'name' => "Thailand", 'iso' => 'THA', 'number' => '764', 'fullname' => "Kingdom of Thailand"),
      (object) array('code' => 'tl', 'continent' => 'AS', 'name' => "Timor-Leste", 'iso' => 'TLS', 'number' => '626', 'fullname' => "Democratic Republic of Timor-Leste"),
      (object) array('code' => 'tg', 'continent' => 'AF', 'name' => "Togo", 'iso' => 'TGO', 'number' => '768', 'fullname' => "Togolese Republic"),
      (object) array('code' => 'tk', 'continent' => 'OC', 'name' => "Tokelau", 'iso' => 'TKL', 'number' => '772', 'fullname' => "Tokelau"),
      (object) array('code' => 'to', 'continent' => 'OC', 'name' => "Tonga", 'iso' => 'TON', 'number' => '776', 'fullname' => "Kingdom of Tonga"),
      (object) array('code' => 'tt', 'continent' => 'NA', 'name' => "Trinidad and Tobago", 'iso' => 'TTO', 'number' => '780', 'fullname' => "Republic of Trinidad and Tobago"),
      (object) array('code' => 'tn', 'continent' => 'AF', 'name' => "Tunisia", 'iso' => 'TUN', 'number' => '788', 'fullname' => "Tunisian Republic"),
      (object) array('code' => 'tr', 'continent' => 'AS', 'name' => "Turkey", 'iso' => 'TUR', 'number' => '792', 'fullname' => "Republic of Turkey"),
      (object) array('code' => 'tm', 'continent' => 'AS', 'name' => "Turkmenistan", 'iso' => 'TKM', 'number' => '795', 'fullname' => "Turkmenistan"),
      (object) array('code' => 'tc', 'continent' => 'NA', 'name' => "Turks and Caicos Islands", 'iso' => 'TCA', 'number' => '796', 'fullname' => "Turks and Caicos Islands"),
      (object) array('code' => 'tv', 'continent' => 'OC', 'name' => "Tuvalu", 'iso' => 'TUV', 'number' => '798', 'fullname' => "Tuvalu"),
      (object) array('code' => 'ug', 'continent' => 'AF', 'name' => "Uganda", 'iso' => 'UGA', 'number' => '800', 'fullname' => "Republic of Uganda"),
      (object) array('code' => 'ua', 'continent' => 'EU', 'name' => "Ukraine", 'iso' => 'UKR', 'number' => '804', 'fullname' => "Ukraine"),
      (object) array('code' => 'ae', 'continent' => 'AS', 'name' => "United Arab Emirates", 'iso' => 'ARE', 'number' => '784', 'fullname' => "United Arab Emirates"),
      (object) array('code' => 'gb', 'continent' => 'EU', 'name' => "United Kingdom of Great Britain & Northern Ireland", 'iso' => 'GBR', 'number' => '826', 'fullname' => "United Kingdom of Great Britain & Northern Ireland"),
      (object) array('code' => 'us', 'continent' => 'NA', 'name' => "United States of America", 'iso' => 'USA', 'number' => '840', 'fullname' => "United States of America"),
      (object) array('code' => 'um', 'continent' => 'OC', 'name' => "United States Minor Outlying Islands", 'iso' => 'UMI', 'number' => '581', 'fullname' => "United States Minor Outlying Islands"),
      (object) array('code' => 'vi', 'continent' => 'NA', 'name' => "United States Virgin Islands", 'iso' => 'VIR', 'number' => '850', 'fullname' => "United States Virgin Islands"),
      (object) array('code' => 'uy', 'continent' => 'SA', 'name' => "Uruguay", 'iso' => 'URY', 'number' => '858', 'fullname' => "Eastern Republic of Uruguay"),
      (object) array('code' => 'uz', 'continent' => 'AS', 'name' => "Uzbekistan", 'iso' => 'UZB', 'number' => '860', 'fullname' => "Republic of Uzbekistan"),
      (object) array('code' => 'vu', 'continent' => 'OC', 'name' => "Vanuatu", 'iso' => 'VUT', 'number' => '548', 'fullname' => "Republic of Vanuatu"),
      (object) array('code' => 've', 'continent' => 'SA', 'name' => "Venezuela", 'iso' => 'VEN', 'number' => '862', 'fullname' => "Bolivarian Republic of Venezuela"),
      (object) array('code' => 'vn', 'continent' => 'AS', 'name' => "Vietnam", 'iso' => 'VNM', 'number' => '704', 'fullname' => "Socialist Republic of Vietnam"),
      (object) array('code' => 'wf', 'continent' => 'OC', 'name' => "Wallis and Futuna", 'iso' => 'WLF', 'number' => '876', 'fullname' => "Wallis and Futuna"),
      (object) array('code' => 'eh', 'continent' => 'AF', 'name' => "Western Sahara", 'iso' => 'ESH', 'number' => '732', 'fullname' => "Western Sahara"),
      (object) array('code' => 'ye', 'continent' => 'AS', 'name' => "Yemen", 'iso' => 'YEM', 'number' => '887', 'fullname' => "Yemen"),
      (object) array('code' => 'zm', 'continent' => 'AF', 'name' => "Zambia", 'iso' => 'ZMB', 'number' => '894', 'fullname' => "Republic of Zambia"),
      (object) array('code' => 'zw', 'continent' => 'AF', 'name' => "Zimbabwe", 'iso' => 'ZWE', 'number' => '716', 'fullname' => "Republic of Zimbabwe")
    );
  }
}
